import Foundation
import PrimuseKit

enum SettingsCatalogData {
    static let items: [SettingDefinition] = [
        SettingDefinition(id: "playback.outputMode", titleKey: "audio_output_mode", iosPage: .playback, macPage: .playback, keywords: ["bit perfect", "DAC", "高保真", "直通", "音质", "无损", "DSP", "Output Mode"]),
        SettingDefinition(id: "playback.dsdMode", titleKey: "dsd_playback_mode", iosPage: .playback, macPage: .playback, keywords: ["DSD Playback"]),
        SettingDefinition(id: "playback.matchSampleRate", titleKey: "output_sr_matching", iosPage: .playback, macPage: .playback, keywords: ["Match Hardware Sample Rate"]),
        SettingDefinition(id: "playback.speed", titleKey: "playback_rate", iosPage: .playback, macPage: .playback, keywords: ["speed", "倍速", "速度", "语速", "播放太快", "Playback Rate"]),
        SettingDefinition(id: "playback.resetSpeed", titleKey: "playback_rate_reset", iosPage: .playback, macPage: nil, anchor: "playback.speed"),
        SettingDefinition(id: "playback.gapless", titleKey: "gapless_playback", iosPage: .playback, macPage: .playback, keywords: ["gapless", "无缝", "曲目间隔", "歌曲衔接", "Gapless Playback"]),
        SettingDefinition(id: "playback.crossfade", titleKey: "crossfade", iosPage: .playback, macPage: .playback, keywords: ["cross fade", "crossfade", "淡入淡出", "歌曲衔接", "转场"]),
        SettingDefinition(id: "playback.crossfadeMode", titleKey: "crossfade_mode", iosPage: .playback, macPage: .playback, keywords: ["Crossfade Mode"], anchor: "playback.crossfade"),
        SettingDefinition(id: "playback.crossfadeDuration", titleKey: "crossfade_duration", iosPage: .playback, macPage: .playback, keywords: ["crossfade_max_duration", "Crossfade Duration"], anchor: "playback.crossfade"),
        SettingDefinition(id: "playback.skipLeadingSilence", titleKey: "skip_leading_silence", iosPage: .playback, macPage: .playback, keywords: ["Skip leading silence"]),
        SettingDefinition(id: "playback.skipTrailingSilence", titleKey: "skip_trailing_silence", iosPage: .playback, macPage: .playback, keywords: ["Skip trailing silence"]),
        SettingDefinition(id: "playback.replayGain", titleKey: "replay_gain", iosPage: .playback, macPage: .playback, keywords: ["ReplayGain", "音量统一", "音量忽大忽小", "响度"]),
        SettingDefinition(id: "playback.replayGainMode", titleKey: "rg_mode", iosPage: .playback, macPage: .playback, keywords: ["RG Mode"], anchor: "playback.replayGain"),
        SettingDefinition(id: "playback.spatialAudio", titleKey: "spatial_audio", iosPage: .playback, macPage: .playback, keywords: ["Spatial Audio"]),
        SettingDefinition(id: "playback.headTracking", titleKey: "spatial_head_tracking", iosPage: .playback, macPage: nil, anchor: "playback.spatialAudio"),
        SettingDefinition(id: "lyrics.lockScreen", titleKey: "lock_screen_lyrics", iosPage: .playback, macPage: nil, keywords: ["lock screen lyrics", "锁屏没歌词", "锁屏歌词", "控制中心歌词", "蓝牙歌词", "车载歌词"]),
        SettingDefinition(id: "playback.prewarmQueue", titleKey: "Prewarm queue head", iosPage: nil, macPage: .playback),
        SettingDefinition(id: "equalizer.enabled", titleKey: "eq_enabled", iosPage: .equalizer, macPage: .equalizer, keywords: ["EQ", "equalizer", "均衡器", "低音", "bass", "treble", "高音", "Enable EQ"]),
        SettingDefinition(id: "equalizer.preset", titleKey: "eq_preset", iosPage: .equalizer, macPage: .equalizer, keywords: ["Current Preset"]),
        SettingDefinition(id: "equalizer.bands", titleKey: "equalizer", iosPage: .equalizer, macPage: .equalizer, keywords: ["EQ bands", "frequency", "频段", "31Hz", "62Hz", "125Hz", "250Hz", "500Hz", "1kHz", "2kHz", "4kHz", "8kHz", "16kHz"]),
        SettingDefinition(id: "equalizer.reset", titleKey: "eq_reset", iosPage: .equalizer, macPage: .equalizer, keywords: ["Reset"]),
        SettingDefinition(id: "effects.reverb", titleKey: "reverb_enabled", iosPage: .effects, macPage: .effects, keywords: ["Toggle"]),
        SettingDefinition(id: "effects.reverbPreset", titleKey: "reverb", iosPage: .effects, macPage: .effects, keywords: ["Type"]),
        SettingDefinition(id: "effects.reverbMix", titleKey: "reverb_mix", iosPage: .effects, macPage: .effects),
        SettingDefinition(id: "effects.compressor", titleKey: "compressor_enabled", iosPage: .effects, macPage: .effects, keywords: ["Toggle"]),
        SettingDefinition(id: "effects.compressorPreset", titleKey: "compressor_limiter", iosPage: .effects, macPage: .effects, keywords: ["Preset"]),
        SettingDefinition(id: "effects.compressorThreshold", titleKey: "compressor_threshold", iosPage: .effects, macPage: .effects),
        SettingDefinition(id: "effects.compressorHeadroom", titleKey: "compressor_headroom", iosPage: .effects, macPage: .effects),
        SettingDefinition(id: "effects.compressorAttack", titleKey: "compressor_attack", iosPage: .effects, macPage: .effects),
        SettingDefinition(id: "effects.compressorRelease", titleKey: "compressor_release", iosPage: .effects, macPage: .effects),
        SettingDefinition(id: "effects.compressorGain", titleKey: "compressor_gain", iosPage: .effects, macPage: .effects),
        SettingDefinition(id: "effects.chain", titleKey: "Enable Effects Chain", iosPage: nil, macPage: .effects),
        SettingDefinition(id: "effects.reverbRoomSize", titleKey: "Room Size", table: "SettingsSearch", iosPage: nil, macPage: .effects),
        SettingDefinition(id: "lyrics.translationEnabled", titleKey: "lyrics_translation_enabled", iosPage: .lyrics, macPage: .lyrics),
        SettingDefinition(id: "lyrics.translationMode", titleKey: "lyrics_translation_mode", iosPage: .lyrics, macPage: .lyrics, anchor: "lyrics.translationEnabled"),
        SettingDefinition(id: "lyrics.translationTarget", titleKey: "lyrics_translation_target", iosPage: .lyrics, macPage: .lyrics, anchor: "lyrics.translationEnabled"),
        SettingDefinition(id: "lyrics.translationCache", titleKey: "lyrics_translation_cached", iosPage: .lyrics, macPage: nil, anchor: "lyrics.translationEnabled"),
        SettingDefinition(id: "lyrics.clearTranslationCache", titleKey: "lyrics_translation_clear_cache", iosPage: .lyrics, macPage: nil, anchor: "lyrics.translationEnabled"),
        SettingDefinition(id: "lyrics.transcription", titleKey: "lyrics_transcription_settings_title", iosPage: .transcription, macPage: .transcription),
        SettingDefinition(id: "lyrics.transcriptionAPIKey", titleKey: "lyrics_transcription_api_key", iosPage: .transcription, macPage: .transcription),
        SettingDefinition(id: "lyrics.transcriptionFetchModels", titleKey: "lyrics_transcription_fetch_models", iosPage: .transcription, macPage: .transcription),
        SettingDefinition(id: "lyrics.transcriptionModel", titleKey: "lyrics_transcription_model", iosPage: .transcription, macPage: .transcription),
        SettingDefinition(id: "lyrics.transcriptionEnabled", titleKey: "lyrics_transcription_enabled", iosPage: .transcription, macPage: .transcription),
        SettingDefinition(id: "lyrics.transcriptionConsent", titleKey: "lyrics_transcription_audio_consent", iosPage: .transcription, macPage: .transcription),
        SettingDefinition(id: "lyrics.transcriptionSave", titleKey: "save", iosPage: .transcription, macPage: .transcription, anchor: "lyrics.transcriptionEnabled"),
        SettingDefinition(id: "lyrics.transcriptionDeleteKey", titleKey: "ai_delete_current_api_key", iosPage: .transcription, macPage: .transcription, anchor: "lyrics.transcriptionAPIKey"),
        SettingDefinition(id: "lyrics.colorMode", titleKey: "player_current_lyric_color", iosPage: .player, macPage: nil, keywords: ["lyrics color", "歌词颜色", "渐变歌词"]),
        SettingDefinition(id: "lyrics.customColor", titleKey: "player_lyrics_custom_color", iosPage: .player, macPage: nil, anchor: "lyrics.colorMode"),
        SettingDefinition(id: "lyrics.gradientStart", titleKey: "player_lyrics_gradient_start_color", iosPage: .player, macPage: nil, anchor: "lyrics.colorMode"),
        SettingDefinition(id: "lyrics.gradientEnd", titleKey: "player_lyrics_gradient_end_color", iosPage: .player, macPage: nil, anchor: "lyrics.colorMode"),
        SettingDefinition(id: "lyrics.alignment", titleKey: "player_lyrics_alignment", iosPage: .player, macPage: nil),
        SettingDefinition(id: "lyrics.blurInactive", titleKey: "player_blur_inactive_lyrics", iosPage: .player, macPage: nil),
        SettingDefinition(id: "lyrics.keepScreenAwake", titleKey: "player_keep_screen_awake_for_lyrics", iosPage: .player, macPage: nil, keywords: ["keep awake", "亮屏", "歌词熄屏", "屏幕常亮"]),
        SettingDefinition(id: "lyrics.tapToSeek", titleKey: "player_tap_lyrics_to_seek", iosPage: .player, macPage: .lyrics),
        SettingDefinition(id: "lyrics.fontSize", titleKey: "lyrics_font_size", iosPage: nil, macPage: .lyrics),
        SettingDefinition(id: "storage.audioCacheEnabled", titleKey: "audio_cache_enabled", iosPage: .storage, macPage: .storage, keywords: ["offline download", "缓存", "离线", "自动下载"]),
        SettingDefinition(id: "storage.audioCacheLimit", titleKey: "audio_cache_limit", iosPage: .storage, macPage: .storage, keywords: ["cache limit", "缓存上限", "存储空间", "下载限制"]),
        SettingDefinition(id: "storage.clearAudioCache", titleKey: "audio_cache", iosPage: .storage, macPage: .storage, keywords: ["clear cache", "清理缓存", "删除缓存", "释放空间", "clear_cache"], macAnchor: "storage.audioCacheLimit"),
        SettingDefinition(id: "storage.clearImageCache", titleKey: "image_cache", iosPage: .storage, macPage: nil),
        SettingDefinition(id: "storage.clearMetadata", titleKey: "cover_art_lyrics", iosPage: .storage, macPage: nil),
        SettingDefinition(id: "storage.clearPartial", titleKey: "cache_partial", iosPage: .storage, macPage: nil, anchor: "storage.clearAudioCache"),
        SettingDefinition(id: "storage.clearOrphaned", titleKey: "cache_orphaned", iosPage: .storage, macPage: nil, anchor: "storage.clearAudioCache"),
        SettingDefinition(id: "storage.wifiOnly", titleKey: "cloud_scan_wifi_only", iosPage: .storage, macPage: nil, keywords: ["wifi", "wi-fi", "cellular", "save data", "省流量", "流量", "手机网络", "蜂窝网络"]),
        SettingDefinition(id: "storage.notifyBackfill", titleKey: "notify_backfill_complete", iosPage: .storage, macPage: nil, keywords: ["notification", "通知", "标签读取完成"]),
        SettingDefinition(id: "storage.retryBackfill", titleKey: "Retry paused tag reading", table: "SettingsSearch", iosPage: .storage, macPage: nil, anchor: "storage.wifiOnly"),
        SettingDefinition(id: "appearance.scheme", titleKey: "appearance", iosPage: .appearance, macPage: .appearance, keywords: ["dark mode", "深色", "浅色", "夜间模式", "Theme"]),
        SettingDefinition(id: "appearance.minimalNavigation", titleKey: "minimal_mode_title", iosPage: .appearance, macPage: nil, keywords: ["minimal", "极简", "导航模式"]),
        SettingDefinition(id: "appearance.themeMode", titleKey: "theme_color_mode", iosPage: .themeColor, macPage: .appearance),
        SettingDefinition(id: "appearance.palette", titleKey: "theme_color_palette", iosPage: .themeColor, macPage: .appearance, keywords: ["Brand Color"]),
        SettingDefinition(id: "appearance.hue", titleKey: "theme_color_hue", iosPage: .themeColor, macPage: nil),
        SettingDefinition(id: "appearance.saturation", titleKey: "theme_color_saturation", iosPage: .themeColor, macPage: nil, anchor: "appearance.hue", macAnchor: "appearance.saturation"),
        SettingDefinition(id: "appearance.brightness", titleKey: "theme_color_brightness", iosPage: .themeColor, macPage: nil, anchor: "appearance.hue", macAnchor: "appearance.brightness"),
        SettingDefinition(id: "appearance.hex", titleKey: "theme_color_hex", iosPage: .themeColor, macPage: nil),
        SettingDefinition(id: "appearance.coverAmbient", titleKey: "ext.tv.settings.coverColor", iosPage: .themeColor, macPage: .appearance, usesKitLocalization: true),
        SettingDefinition(id: "appearance.ambientStrength", titleKey: "ext.tv.settings.ambientIntensity", iosPage: .themeColor, macPage: .appearance, usesKitLocalization: true),
        SettingDefinition(id: "appearance.animatedArtwork", titleKey: "player_animated_artwork", iosPage: .player, macPage: .appearance),
        SettingDefinition(id: "appearance.animatedArtworkUnmeteredOnly", titleKey: "player_animated_artwork_unmetered_only", iosPage: .player, macPage: .appearance),
        SettingDefinition(id: "appearance.motionArtworkService", titleKey: "motion_artwork_service_enabled", iosPage: .player, macPage: .appearance, keywords: ["animated artwork", "动态封面", "服务端点"]),
        SettingDefinition(id: "appearance.motionArtworkEndpoint", titleKey: "motion_artwork_service_endpoint", iosPage: .player, macPage: .appearance, keywords: ["animated artwork URL", "动态封面地址"]),
        SettingDefinition(id: "appearance.volumeBar", titleKey: "player_volume_bar", iosPage: .player, macPage: .appearance),
        SettingDefinition(id: "appearance.fullscreenEffect", titleKey: "fullscreen_effect_settings_title", iosPage: .fullscreen, macPage: .appearance, keywords: ["visualizer", "spectrum", "可视化", "频谱", "全屏效果"]),
        SettingDefinition(id: "appearance.lyricsMotion", titleKey: "immersive_lyrics_motion_title", iosPage: .fullscreen, macPage: nil),
        SettingDefinition(id: "appearance.appIcon", titleKey: "app_icon", iosPage: .appIcon, macPage: .appearance),
        SettingDefinition(id: "appearance.material", titleKey: "Material", table: "SettingsSearch", iosPage: nil, macPage: .appearance),
        SettingDefinition(id: "appearance.autoMaterial", titleKey: "Detect macOS version automatically at launch", table: "SettingsSearch", iosPage: nil, macPage: .appearance),
        SettingDefinition(id: "home.radio", titleKey: "radio_home_visibility", iosPage: .home, macPage: .appearance),
        SettingDefinition(id: "home.order", titleKey: "home_settings_sections_label", iosPage: .home, macPage: nil),
        SettingDefinition(id: "home.restoreOrder", titleKey: "home_settings_restore_default_order", iosPage: .home, macPage: nil),
        SettingDefinition(id: "home.continueListening", titleKey: "home_section_continue_listening", iosPage: .home, macPage: nil),
        SettingDefinition(id: "home.quickAccess", titleKey: "home_section_quick_access", iosPage: .home, macPage: nil),
        SettingDefinition(id: "home.forYou", titleKey: "home_section_for_you", iosPage: .home, macPage: nil),
        SettingDefinition(id: "home.playlists", titleKey: "home_section_playlists", iosPage: .home, macPage: nil),
        SettingDefinition(id: "home.topArtists", titleKey: "home_section_top_artists", iosPage: .home, macPage: nil),
        SettingDefinition(id: "home.recentlyAdded", titleKey: "recent_albums", table: "HomeDiscovery", iosPage: .home, macPage: .appearance),
        SettingDefinition(id: "home.stats", titleKey: "stats_title", iosPage: .home, macPage: nil),
        SettingDefinition(id: "library.quickAccessCount", titleKey: "library_quick_access_count", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.quickAccessCoverStyle", titleKey: "library_quick_access_cover_style", iosPage: .libraryDisplay, macPage: .appearance, keywords: ["封面", "圆形", "方形", "多图", "拼图", "cover", "circle", "square", "collage"]),
        SettingDefinition(id: "library.flatBrowse", titleKey: "library_default_flat_view", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.sectionOrder", titleKey: "library_sections_settings_label", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.restoreOrder", titleKey: "library_sections_restore_default_order", iosPage: .libraryDisplay, macPage: .appearance, macAnchor: "library.sectionOrder"),
        SettingDefinition(id: "library.recommendationDirections", titleKey: "ai_recommendation_intents_settings_title", iosPage: .libraryDisplay, macPage: .appearance, keywords: ["智能推荐", "选歌方向", "推荐偏好"]),
        SettingDefinition(id: "library.restoreRecommendationPresets", titleKey: "ai_recommendation_presets_restore", iosPage: .libraryDisplay, macPage: .appearance, anchor: "library.recommendationDirections"),
        SettingDefinition(id: "library.customDirectionTitle", titleKey: "ai_recommendation_custom_title_placeholder", iosPage: .libraryDisplay, macPage: .appearance, anchor: "library.recommendationDirections"),
        SettingDefinition(id: "library.customDirectionPrompt", titleKey: "ai_recommendation_custom_prompt_placeholder", iosPage: .libraryDisplay, macPage: .appearance, anchor: "library.recommendationDirections"),
        SettingDefinition(id: "library.addDirection", titleKey: "ai_recommendation_custom_add", iosPage: .libraryDisplay, macPage: .appearance, anchor: "library.recommendationDirections"),
        SettingDefinition(id: "library.removeDirection", titleKey: "ai_recommendation_custom_remove", iosPage: .libraryDisplay, macPage: .appearance, anchor: "library.recommendationDirections"),
        SettingDefinition(id: "library.show.recommendations", titleKey: "library_recommendations_title", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.playlists", titleKey: "tab_playlists", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.artists", titleKey: "tab_artists", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.genres", titleKey: "tab_genres", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.albums", titleKey: "tab_albums", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.songs", titleKey: "tab_songs", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.radio", titleKey: "radio_title", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.favorites", titleKey: "library_quick_access", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.folders", titleKey: "library_browse_folder", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "library.show.statistics", titleKey: "stats_title", iosPage: .libraryDisplay, macPage: .appearance),
        SettingDefinition(id: "artists.separators", titleKey: "artist_name_settings_separators", iosPage: .artists, macPage: .artists, keywords: ["artist_name_settings_separator_placeholder", "add"]),
        SettingDefinition(id: "artists.protectedNames", titleKey: "artist_name_settings_protected_names", iosPage: .artists, macPage: .artists, keywords: ["artist_name_settings_protected_placeholder", "add"]),
        SettingDefinition(id: "artists.displaySeparator", titleKey: "artist_name_settings_display_separator", iosPage: .artists, macPage: .artists, keywords: ["artist_name_settings_display_separator_placeholder", "save"]),
        SettingDefinition(id: "artists.reset", titleKey: "artist_name_settings_reset", iosPage: .artists, macPage: .artists, anchor: "artists.separators"),
        SettingDefinition(id: "scraping.sources", titleKey: "scraper_sources", iosPage: .scraping, macPage: .scraping, keywords: ["Scraping Sources"]),
        SettingDefinition(id: "scraping.import", titleKey: "import_scraper_source", iosPage: .scraping, macPage: .scraping, keywords: ["Import"]),
        SettingDefinition(id: "scraping.onlyMissing", titleKey: "only_fill_missing", iosPage: .scraping, macPage: .scraping, keywords: ["Fill Missing Fields Only"]),
        SettingDefinition(id: "scraping.reset", titleKey: "reset_scraper_defaults", iosPage: .scraping, macPage: .scraping, keywords: ["Restore Defaults"]),
        SettingDefinition(id: "scraping.fillMissing", titleKey: "scrape_missing_metadata", iosPage: .scraping, macPage: .scraping, keywords: ["Fill Missing"]),
        SettingDefinition(id: "scraping.rescrape", titleKey: "rescrape_library", iosPage: .scraping, macPage: .scraping, keywords: ["Re-Scrape"], macAnchor: "scraping.fillMissing"),
        SettingDefinition(id: "scraping.cancel", titleKey: "cancel", iosPage: .scraping, macPage: .scraping, keywords: ["Cancel"], anchor: "scraping.fillMissing"),
        SettingDefinition(id: "scraping.cookie", titleKey: "cookie_config", iosPage: .scraping, macPage: nil, keywords: ["cookie_placeholder", "cookie_config_message", "save"], anchor: "scraping.sources"),
        SettingDefinition(id: "scraping.editCustomJSON", titleKey: "custom_sources", iosPage: .scraping, macPage: nil, anchor: "scraping.sources"),
        SettingDefinition(id: "scraping.shareCustom", titleKey: "share", iosPage: .scraping, macPage: nil, anchor: "scraping.sources"),
        SettingDefinition(id: "scraping.writeCover", titleKey: "Cover Write-Back", iosPage: nil, macPage: .scraping),
        SettingDefinition(id: "scraping.writeLyrics", titleKey: "Lyrics Write-Back", iosPage: nil, macPage: .scraping),
        SettingDefinition(id: "scraping.writeTimeout", titleKey: "Write Timeout", iosPage: nil, macPage: .scraping),
        SettingDefinition(id: "intelligence.relay", titleKey: "ai_primuse_relay_enabled", iosPage: .intelligence, macPage: .intelligence),
        SettingDefinition(id: "intelligence.relayTest", titleKey: "ai_primuse_relay_test_connection", iosPage: .intelligence, macPage: .intelligence),
        SettingDefinition(id: "intelligence.semanticSearch", titleKey: "ai_enable_semantic_search", iosPage: .intelligence, macPage: .intelligence),
        SettingDefinition(id: "intelligence.recommendations", titleKey: "ai_enable_recommendations", iosPage: .intelligence, macPage: .intelligence),
        SettingDefinition(id: "intelligence.providers", titleKey: "ai_provider_list_section", iosPage: .intelligence, macPage: .intelligence),
        SettingDefinition(id: "intelligence.fallback", titleKey: "ai_fallback_enabled", iosPage: .intelligence, macPage: .intelligence),
        SettingDefinition(id: "intelligence.addProvider", titleKey: "ai_add_provider", iosPage: .intelligence, macPage: .intelligence),
        SettingDefinition(id: "intelligence.primaryProvider", titleKey: "ai_set_primary", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.providerOrder", titleKey: "ai_move_up", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.removeProvider", titleKey: "ai_remove_provider", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.providerDetails", titleKey: "ai_provider_detail_section", iosPage: .intelligence, macPage: .intelligence, keywords: ["ai_edit_provider"], anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.providerPreset", titleKey: "ai_provider_preset", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.providerName", titleKey: "ai_provider_name", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.baseURL", titleKey: "ai_base_url", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.compatibility", titleKey: "ai_compatibility_mode", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.apiKey", titleKey: "ai_api_key", iosPage: .intelligence, macPage: .intelligence, keywords: ["ai_openai_platform_api_key"], anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.generationModel", titleKey: "ai_generation_model", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.embeddingModel", titleKey: "ai_embedding_model", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.fetchModels", titleKey: "ai_fetch_models", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.remoteConsent", titleKey: "ai_remote_consent", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.listeningContextConsent", titleKey: "ai_listening_context_consent", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.insecureHTTP", titleKey: "ai_allow_insecure_local_http", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.testConnection", titleKey: "ai_test_connection", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "intelligence.deleteAPIKey", titleKey: "ai_delete_current_api_key", iosPage: .intelligence, macPage: .intelligence, anchor: "intelligence.providers", hint: "Choose a provider to configure this setting."),
        SettingDefinition(id: "appleMusic.authorize", titleKey: "settings_apple_music_connect", iosPage: .appleMusic, macPage: .appleMusic, keywords: ["Authorize"]),
        SettingDefinition(id: "appleMusic.systemSettings", titleKey: "open_system_settings", iosPage: .appleMusic, macPage: .appleMusic, keywords: ["Open System Settings"], anchor: "appleMusic.authorize"),
        SettingDefinition(id: "appleMusic.sync", titleKey: "apple_music_library_sync", iosPage: .appleMusic, macPage: .appleMusic, keywords: ["Re-Sync"], hint: "Manage Apple Music authorization and sync on this page."),
        SettingDefinition(id: "appleMusic.syncUserLibrary", titleKey: "Sync User Library", table: "SettingsSearch", iosPage: nil, macPage: .appleMusic),
        SettingDefinition(id: "appleMusic.catalogSearch", titleKey: "Catalog Search", table: "SettingsSearch", iosPage: nil, macPage: .appleMusic),
        SettingDefinition(id: "appleMusic.autoSmartPlaylists", titleKey: "Auto Add to Smart Playlists", table: "SettingsSearch", iosPage: nil, macPage: .appleMusic),
        SettingDefinition(id: "scrobble.enabled", titleKey: "scrobble_enabled", iosPage: .scrobble, macPage: nil),
        SettingDefinition(id: "scrobble.nowPlaying", titleKey: "scrobble_send_now_playing", iosPage: .scrobble, macPage: nil),
        SettingDefinition(id: "scrobble.listenBrainz", titleKey: "ListenBrainz", iosPage: .scrobble, macPage: nil),
        SettingDefinition(id: "scrobble.listenBrainzToken", titleKey: "scrobble_lb_token_placeholder", iosPage: .scrobble, macPage: nil, keywords: ["scrobble_user_token", "save", "scrobble_user_token"], anchor: "scrobble.listenBrainz"),
        SettingDefinition(id: "scrobble.validateListenBrainz", titleKey: "scrobble_validate", iosPage: .scrobble, macPage: nil, anchor: "scrobble.listenBrainz"),
        SettingDefinition(id: "scrobble.getListenBrainzToken", titleKey: "scrobble_lb_get_token", iosPage: .scrobble, macPage: nil, anchor: "scrobble.listenBrainz"),
        SettingDefinition(id: "scrobble.lastFM", titleKey: "Last.fm", iosPage: .scrobble, macPage: nil),
        SettingDefinition(id: "scrobble.connectLastFM", titleKey: "scrobble_lastfm_connect", iosPage: .scrobble, macPage: nil, anchor: "scrobble.lastFM"),
        SettingDefinition(id: "scrobble.signOutLastFM", titleKey: "scrobble_lastfm_signout", iosPage: .scrobble, macPage: nil, anchor: "scrobble.lastFM"),
        SettingDefinition(id: "scrobble.reopenLastFMAuthorization", titleKey: "scrobble_lastfm_reopen_authorization", iosPage: .scrobble, macPage: nil, anchor: "scrobble.lastFM"),
        SettingDefinition(id: "scrobble.confirmLastFMAuthorization", titleKey: "scrobble_lastfm_confirm_authorized", iosPage: .scrobble, macPage: nil, keywords: ["scrobble_mac_i_authorized"], anchor: "scrobble.lastFM"),
        SettingDefinition(id: "scrobble.cancelLastFMAuthorization", titleKey: "scrobble_lastfm_cancel_pending", iosPage: .scrobble, macPage: nil, anchor: "scrobble.lastFM"),
        SettingDefinition(id: "scrobble.lastFMAdvanced", titleKey: "scrobble_lastfm_advanced_title", iosPage: .scrobble, macPage: nil),
        SettingDefinition(id: "scrobble.lastFMAPIKey", titleKey: "scrobble_lastfm_api_key_placeholder", iosPage: .scrobble, macPage: nil, keywords: ["api_key"], anchor: "scrobble.lastFMAdvanced"),
        SettingDefinition(id: "scrobble.lastFMAPISecret", titleKey: "scrobble_lastfm_api_secret_placeholder", iosPage: .scrobble, macPage: nil, keywords: ["scrobble_api_secret"], anchor: "scrobble.lastFMAdvanced"),
        SettingDefinition(id: "scrobble.registerLastFMApp", titleKey: "scrobble_lastfm_register_app", iosPage: .scrobble, macPage: nil, keywords: ["scrobble_mac_create_api_app"], anchor: "scrobble.lastFMAdvanced"),
        SettingDefinition(id: "scrobble.retryQueue", titleKey: "scrobble_retry_now", iosPage: .scrobble, macPage: nil),
        SettingDefinition(id: "scrobble.clearQueue", titleKey: "scrobble_clear_queue", iosPage: .scrobble, macPage: nil),
        SettingDefinition(id: "cloud.enabled", titleKey: "icloud_sync_enabled", iosPage: .cloud, macPage: .cloud),
        SettingDefinition(id: "cloud.status", titleKey: "icloud_sync_status", iosPage: .cloud, macPage: .cloud, keywords: ["Sync Status"]),
        SettingDefinition(id: "cloud.systemSettings", titleKey: "open_system_settings", iosPage: .cloud, macPage: .cloud, keywords: ["Open System Settings"], anchor: "cloud.status"),
        SettingDefinition(id: "cloud.syncNow", titleKey: "sync_now", iosPage: .cloud, macPage: .cloud, keywords: ["Sync Now"], macAnchor: "cloud.status"),
        SettingDefinition(id: "cloud.playlists", titleKey: "synced_playlists", iosPage: .cloud, macPage: .cloud),
        SettingDefinition(id: "cloud.sources", titleKey: "synced_sources", iosPage: .cloud, macPage: .cloud),
        SettingDefinition(id: "cloud.playbackHistory", titleKey: "synced_playback_history", iosPage: .cloud, macPage: .cloud),
        SettingDefinition(id: "cloud.settings", titleKey: "synced_settings", iosPage: .cloud, macPage: .cloud),
        SettingDefinition(id: "cloud.credentials", titleKey: "synced_credentials", iosPage: .cloud, macPage: .cloud),
        SettingDefinition(id: "cloud.listeningStats", titleKey: "stats_title", iosPage: .cloud, macPage: .cloud),
        SettingDefinition(id: "family.create", titleKey: "family_sharing_create", iosPage: .family, macPage: .cloud, keywords: ["Create"]),
        SettingDefinition(id: "family.manage", titleKey: "family_sharing_manage", iosPage: .family, macPage: .cloud, keywords: ["Invite…"], anchor: "family.create"),
        SettingDefinition(id: "family.leave", titleKey: "family_sharing_leave", iosPage: .family, macPage: .cloud, keywords: ["Off"], macAnchor: "family.create"),
        SettingDefinition(id: "cacheSync.inventory", titleKey: "cache_sync_local_cache", table: "CacheSync", iosPage: .cacheSync, macPage: .cacheSync, anchor: "page.cacheSync", macAnchor: "cacheSync.inventory", hint: "Select a nearby device to view its available transfer actions."),
        SettingDefinition(id: "cacheSync.refreshPeers", titleKey: "cache_sync_refresh", table: "CacheSync", iosPage: .cacheSync, macPage: .cacheSync, anchor: "page.cacheSync", macAnchor: "cacheSync.refreshPeers", hint: "Select a nearby device to view its available transfer actions."),
        SettingDefinition(id: "cacheSync.compare", titleKey: "cache_sync_tap_to_compare", table: "CacheSync", iosPage: .cacheSync, macPage: .cacheSync, anchor: "page.cacheSync", macAnchor: "cacheSync.compare", hint: "Select a nearby device to view its available transfer actions."),
        SettingDefinition(id: "cacheSync.testThree", titleKey: "cache_sync_test_three", table: "CacheSync", iosPage: .cacheSync, macPage: .cacheSync, anchor: "page.cacheSync", macAnchor: "cacheSync.testThree", hint: "Select a nearby device to view its available transfer actions."),
        SettingDefinition(id: "cacheSync.syncAll", titleKey: "cache_sync_sync_all", table: "CacheSync", iosPage: .cacheSync, macPage: .cacheSync, anchor: "page.cacheSync", macAnchor: "cacheSync.syncAll", hint: "Select a nearby device to view its available transfer actions."),
        SettingDefinition(id: "cacheSync.stop", titleKey: "cache_sync_stop", table: "CacheSync", iosPage: .cacheSync, macPage: .cacheSync, anchor: "page.cacheSync", macAnchor: "cacheSync.stop", hint: "Select a nearby device to view its available transfer actions."),
        SettingDefinition(id: "cacheSync.retry", titleKey: "cache_sync_retry", table: "CacheSync", iosPage: .cacheSync, macPage: .cacheSync, anchor: "page.cacheSync", macAnchor: "cacheSync.retry", hint: "Select a nearby device to view its available transfer actions."),
        SettingDefinition(id: "dlna.enabled", titleKey: "settings_dlna_enable", iosPage: .dlna, macPage: nil),
        SettingDefinition(id: "dlna.keepAlive", titleKey: "settings_dlna_keepalive", iosPage: .dlna, macPage: nil),
        SettingDefinition(id: "dlna.devices", titleKey: "settings_dlna_devices_section", iosPage: .dlna, macPage: nil),
        SettingDefinition(id: "relay.enabled", titleKey: "settings_relay_enable", iosPage: .relay, macPage: nil),
        SettingDefinition(id: "appleTV.push", titleKey: "settings_push_to_tv", iosPage: .appleTV, macPage: nil),
        SettingDefinition(id: "siri.authorization", titleKey: "Siri authorization", table: "SettingsSearch", iosPage: .siri, macPage: nil),
        SettingDefinition(id: "siri.shortcuts", titleKey: "siri_shortcuts_hint", iosPage: .siri, macPage: nil),
        SettingDefinition(id: "security.httpsTrust", titleKey: "https_certificate_trust", iosPage: .domains, macPage: .domains, keywords: ["Trusted self-signed certificates"]),
        SettingDefinition(id: "security.addTrustedDomain", titleKey: "add_trusted_domain", iosPage: .domains, macPage: .domains, keywords: ["domain_placeholder", "add_trusted_domain_message", "Add Domain"]),
        SettingDefinition(id: "security.httpDomains", titleKey: "insecure_http_domains", iosPage: .domains, macPage: nil),
        SettingDefinition(id: "security.addHTTPDomain", titleKey: "add_insecure_http_domain", iosPage: .domains, macPage: nil, keywords: ["domain_placeholder", "allow_insecure_http", "add_insecure_http_domain_message"]),
        SettingDefinition(id: "deleted.playlists", titleKey: "recently_deleted_playlists", iosPage: .deleted, macPage: .deleted),
        SettingDefinition(id: "deleted.smartPlaylists", titleKey: "recently_deleted_smart_playlists", iosPage: .deleted, macPage: .deleted),
        SettingDefinition(id: "deleted.sources", titleKey: "recently_deleted_sources", iosPage: .deleted, macPage: .deleted),
        SettingDefinition(id: "deleted.scraperConfigs", titleKey: "recently_deleted_scraper_configs", iosPage: .deleted, macPage: .deleted),
        SettingDefinition(id: "deleted.hiddenPlaylists", titleKey: "hidden_source_playlists", iosPage: .deleted, macPage: .deleted),
        SettingDefinition(id: "deleted.clearAll", titleKey: "clear_all", iosPage: .deleted, macPage: .deleted),
        SettingDefinition(id: "keyboard.restoreDefaults", titleKey: "keyboard_shortcuts_restore_defaults", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.clearShortcut", titleKey: "keyboard_shortcuts_clear", iosPage: nil, macPage: .keyboard, macAnchor: "page.keyboard"),
        SettingDefinition(id: "keyboard.playPause", titleKey: "play_pause", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.nextTrack", titleKey: "next_song", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.previousTrack", titleKey: "previous_song", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.shuffle", titleKey: "shuffle", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.repeatMode", titleKey: "repeat", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.volumeUp", titleKey: "volume_up", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.volumeDown", titleKey: "volume_down", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.focusSearch", titleKey: "search_title", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.showMiniPlayer", titleKey: "mini_player", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.showDesktopLyrics", titleKey: "show_desktop_lyrics", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "keyboard.toggleDesktopLyricsLock", titleKey: "toggle_desktop_lyrics_lock", iosPage: nil, macPage: .keyboard),
        SettingDefinition(id: "widgets.enabled", titleKey: "desktop_widget_sync_enabled", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.refreshFrequency", titleKey: "Refresh Frequency", table: "SettingsSearch", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.sharedData", titleKey: "Shared Data Scope", table: "SettingsSearch", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.clickable", titleKey: "Clickable Interaction", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.refreshNow", titleKey: "desktop_widget_sync_update_now", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.nowPlaying", titleKey: "Now Playing", table: "SettingsSearch", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.lyrics", titleKey: "Lyrics", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.stats", titleKey: "Listening Stats", table: "SettingsSearch", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.recent", titleKey: "carplay_tab_recent", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.sources", titleKey: "sources_title", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "widgets.wrapped", titleKey: "Wrapped", table: "SettingsSearch", iosPage: nil, macPage: .widgets),
        SettingDefinition(id: "about.version", titleKey: "version", iosPage: .about, macPage: .about),
        SettingDefinition(id: "about.build", titleKey: "build", iosPage: .about, macPage: .about, macAnchor: "about.version"),
        SettingDefinition(id: "about.update", titleKey: "check_for_updates", iosPage: .about, macPage: .about, keywords: ["Check for Updates"]),
        SettingDefinition(id: "about.diagnostics", titleKey: "diagnostics_title", iosPage: .diagnostics, macPage: .about, keywords: ["Diagnostic Logs…"], anchor: "page.diagnostics", macAnchor: "about.update"),
        SettingDefinition(id: "about.licenses", titleKey: "licenses", iosPage: .licenses, macPage: .about, keywords: ["Open-Source Licenses…"], anchor: "page.licenses", macAnchor: "about.update"),
        SettingDefinition(id: "about.rate", titleKey: "rate_on_app_store", iosPage: .about, macPage: .about, macAnchor: "about.update"),
        SettingDefinition(id: "about.repository", titleKey: "github_repository", iosPage: .about, macPage: .about),
        SettingDefinition(id: "about.feedback", titleKey: "github_feedback", iosPage: .about, macPage: .about, macAnchor: "about.repository"),
        SettingDefinition(id: "diagnostics.shareReport", titleKey: "diagnostics_title", iosPage: .diagnostics, macPage: nil, anchor: "page.diagnostics", macAnchor: "diagnostics.shareReport", hint: "Choose a diagnostic report to share. Reports appear here when available."),
        SettingDefinition(id: "diagnostics.clearReports", titleKey: "diagnostics_clear", iosPage: .diagnostics, macPage: nil),
        SettingDefinition(id: "stats.source", titleKey: "stats_data_source", iosPage: .statistics, macPage: nil),
        SettingDefinition(id: "stats.range", titleKey: "stats_range", iosPage: .statistics, macPage: nil),
        SettingDefinition(id: "stats.rank", titleKey: "rank_by", iosPage: .statistics, macPage: nil),
        SettingDefinition(id: "stats.clear", titleKey: "stats_clear_action", iosPage: .statistics, macPage: nil),
        SettingDefinition(id: "stats.serverRank", titleKey: "stats_top_header", iosPage: .statistics, macPage: nil),
        SettingDefinition(id: "stats.serverRefresh", titleKey: "stats_server_refresh", iosPage: .statistics, macPage: nil),
        SettingDefinition(id: "duplicates.showAll", titleKey: "Show all duplicate groups", table: "SettingsSearch", iosPage: .duplicates, macPage: nil),
        SettingDefinition(id: "duplicates.cleanAll", titleKey: "dup_clean_all_action", iosPage: .duplicates, macPage: nil),
        SettingDefinition(id: "duplicates.keepBest", titleKey: "dup_keep_best_action_short", iosPage: .duplicates, macPage: nil),
    ]
}
